name: Build Workflow

on:
  push:
    branches:
      - main
      - devel

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-linux
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: ./setup.sh
    - run: ./build.sh -p Android  -t 4
    - run: ./pack.sh
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-android
        path: ./build/Android.zip
