name: updated build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run setup script for Linux
        run: |
          chmod +x ./setup.sh
          ./setup.sh
      - name: Run build script for Linux
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload build artifacts for Linux
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-linux
          path:  |
          ./build/Android
           ./build/pack
          
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run build script for Windows
        run: |
          .\build.bat
      - name: Upload build artifacts for Windows
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: |
               ./build/Windows
               ./build/pack
             
