name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Set up environment
      run: chmod +x Setup.sh && ./Setup.sh

    - name: Build project
      run: chmod +x Build.sh && ./Build.sh -p Android -m your_material_file -t 4
      
